name: Go
on: [pull_request]
jobs:
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Test
      run: go test -gcflags=-l
  test-macos:
    name: Test on Mac
    runs-on: macos-latest
    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Test
      run: go test -gcflags=-l
  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Test
      run: go test -gcflags=-l
