name: Go
on: [pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
        version: ["1.18", "1.19", "1.20", "1.21", "1.22"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.version }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Test
        run: go test -gcflags='all=-N -l'
